# documentation of example data
#
# Data documentation
#

#' @name ExampleData
#' @aliases fuda fuda1 fuda2
#' @title Example data
#' @description Three data sets for use in the examples: objects of class \code{\link{fdsample}},  
#' generated by simulation.
#' @docType data
# usage data(ExampleData) 
#' @details Regression type data with normal distributed \eqn{y}-values. Mean values:
#' \tabular{ll}{
#' \code{fuda}  \tab{mean \eqn{y = x^2}}\cr
#' \code{fuda1} \tab{mean \eqn{y = 4 - x^2}}\cr
#' \code{fuda2} \tab{mean \eqn{y = 4.2 - 1.2 x^2 }}\cr
#' }
# @author Ute Hahn,  \email{ute@@imf.au.dk}
 NULL


#' @name CanadianTemperatures
#' @aliases TempAtla TempCont
#' @title Canadian Temperature Data
#' @description Daily temperature averages at weather stations in Canada. 
#' Data  imported and converted from the package \code{fda}.
#' @docType data
# usage data(exampledata) 
#' @details Two objects of class \code{\link{fdsample}}:
#' \itemize{
#' \item \code{TempAtla} data from 15 weather stations with atlantic climate,
#' \item \code{TempCont} data from 12 weather stations with continental climate.
#' }
#' @examples
#' data(CanadianTemperatures)
#' 
#' # plot summary of the data together with 80% pointwise envelopes
#' 
#' summaryplot(TempAtla, light=.4, envprob=.8, col="seagreen")
#' summaryplot(TempCont, light=.4, envprob=.8, col="brown", add = TRUE)
#' 
#' # replot atlantic temperatures without envelope to uncover the lines
#' 
#' summaryplot(TempAtla, light=.4, col="seagreen", add = TRUE)
NULL


#' @name DeltaKBronze
#' @aliases DeltaKBronze.s DeltaKBronze.t
#' @title Delta K_dir estimates for bronzefilter point pattern
#' @description Delta K_dir estimates for \pkg{spatstat} point pattern \code{bronzefilter}, 
#' as in Hahn & Jensen (2013)
#' @docType data
# usage data(DeltaKBronze) 
#' @details Two list of two \code{\link{fdsample}}-objects, corresponding to the Delta K_dir function
#' estimated on two subsets of the bronze filter point pattern, see Hahn & Jensen (2013).
#' The data sets \code{DeltaKBronze.s} and \code{DeltaKBronze.t} contain estimates of 
#' the rescaled and retransformed Delta K_dir function, respectively.
#' 
#'  The list have elements \code{high}  and \code{low} for the functions estimated high and 
#'  low point density subsets of the point pattern.
#' @examples
#' data(DeltaKBronze)
#' 
#' # plot summary for rescaled DeltaK_dir
#' 
#' summaryplot(DeltaKBronze.s$high, col="red")
#' summaryplot(DeltaKBronze.s$low,  col="blue", add = TRUE)
#'
#' # test significance
#' 
#' with(DeltaKBronze.t, studpermute.test(high, low))

NULL