# documentation of example data
#
# Data documentation
#

#' @name exampledata
#' @aliases xyda xyda1 xyda2
#' @title Example data
#' @description Three data sets for use in the examples: objects of class \code{\link{xydata}},  
#' generated by simulation.
#' @docType data
# usage data(exampledata) 
#' @details Regression type data with normal distributed \eqn{y}-values. Mean values:
#' \tabular{ll}{
#' \code{xyda}  \tab{mean \eqn{y = x^2}}\cr
#' \code{xyda1} \tab{mean \eqn{y = 4 - x^2}}\cr
#' \code{xyda2} \tab{mean \eqn{y = 4.2 - 1.2 x^2 }}\cr
#' }
# @author Ute Hahn,  \email{ute@@imf.au.dk}
 NULL


#' @name CanadianTemperatures
#' @aliases TempAtla TempCont
#' @title Canadian Temperature Data
#' @description Daily temperature averages at weather stations in Canada. 
#' Data  imported and converted from the package \code{fda}.
#' @docType data
# usage data(exampledata) 
#' @details Two objects of class \code{\link{fdsample}}:
#' \itemize{
#' \item \code{TempAtla} data from 15 weather stations with atlantic climate,
#' \item \code{TempCont} data from 12 weather stations with continental climate.
#' }
#' @examples
#' data(CanadianTemperatures)
#' 
#' # plot summary the data together with 80% pointwise envelopes
#' 
#' summaryplot(TempAtla, light=.4, envprob=.8, col="seagreen")
#' summaryplot(TempCont, light=.4, envprob=.8, col="brown", add = TRUE)
#' 
#' # replot atlantic temperatures without envelope to uncover the lines
#' 
#' summaryplot(TempAtla, light=.4, col="seagreen", add = TRUE)
NULL