# documentation of example data
#
# Data documentation
#

#' @name exampledata
#' @aliases xyda xyda1 xyda2
#' @title Example data
#' @description Three data sets for use in the examples: objects of class \code{\link{xydata}},  
#' generated by simulation.
#' @docType data
# usage data(exampledata) 
#' @details Regression type data with normal distributed \eqn{y}-values. Mean values:
#' \tabular{ll}{
#' \code{xyda}  \tab{mean \eqn{y = x^2}}\cr
#' \code{xyda1} \tab{mean \eqn{y = 4 - x^2}}\cr
#' \code{xyda2} \tab{mean \eqn{y = 4.2 - 1.2 x^2 }}\cr
#' }
#' @author Ute Hahn,  \email{ute@@imf.au.dk}
 NULL